// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;

namespace AeonLabs.Layouts.StartUp.My.Resources
{

    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode()]
    [System.Runtime.CompilerServices.CompilerGenerated()]
    internal class strings
    {
        private static System.Resources.ResourceManager resourceMan;
        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() : base()
        {
        }

        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (ReferenceEquals(resourceMan, null))
                {
                    var temp = new System.Resources.ResourceManager("AeonLabs.Layouts.StartUp.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }

                return resourceMan;
            }
        }

        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }

            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        /// Looks up a localized string similar to code.
        /// </summary>
        internal static string accessCode
        {
            get
            {
                return ResourceManager.GetString("accessCode", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to cancel.
        /// </summary>
        internal static string cancelBtn
        {
            get
            {
                return ResourceManager.GetString("cancelBtn", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to ID.
        /// </summary>
        internal static string cardId
        {
            get
            {
                return ResourceManager.GetString("cardId", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to connecting to Cloud service.
        /// </summary>
        internal static string commServer
        {
            get
            {
                return ResourceManager.GetString("commServer", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to loading.
        /// </summary>
        internal static string loading
        {
            get
            {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to authentication error.
        /// </summary>
        internal static string loginFailed
        {
            get
            {
                return ResourceManager.GetString("loginFailed", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Pass smartcard.
        /// </summary>
        internal static string passCardOnReader
        {
            get
            {
                return ResourceManager.GetString("passCardOnReader", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Question.
        /// </summary>
        internal static string question
        {
            get
            {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to .
        /// </summary>
        internal static string s
        {
            get
            {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to Try again.
        /// </summary>
        internal static string tryAgain
        {
            get
            {
                return ResourceManager.GetString("tryAgain", resourceCulture);
            }
        }

        /// <summary>
        /// Looks up a localized string similar to version.
        /// </summary>
        internal static string Version
        {
            get
            {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}